### ISSUE TITLE
[BUG] Multiple exceptions parsing templates that are otherwise valid

### ISSUE THREAD

**Issue by pamelafox** [Azure/template-analyzer#326]
### Describe the bug

I am attempting to use template analyzer on this AZD (Azure Developer CLI) template:
https://github.com/pamelafox/simple-fastapi-container/pull/6/files

I am using it via the Github action, which does directory analysis by default. The workflow fails due to exceptions, and there are 30 exceptions in the logs:
https://github.com/pamelafox/simple-fastapi-container/actions/runs/4485874775/jobs/7887846943

Here's an example exception:

```
    Exception details:
    Azure.Deployments.Core.Exceptions.ExpressionException: The language expression property 'outputs' can't be evaluated.
       at Azure.Deployments.Expression.Expressions.FunctionExpression.SelectProperty(JToken root, JToken property, TemplateErrorAdditionalInfo additionalInfo)
       at Azure.Deployments.Expression.Expressions.FunctionExpression.EvaluateExpression(ExpressionEvaluationContext context, TemplateErrorAdditionalInfo additionalInfo)
       at Azure.Deployments.Expression.Engines.ExpressionsEngine.EvaluateLanguageExpressionsInternal(JToken root, ExpressionEvaluationContext evaluationContext, Boolean ignoreExceptions, TemplateErrorAdditionalInfo additionalInfo, InsensitiveHashSet skipEvaluationPaths)
       at Azure.Deployments.Expression.Engines.ExpressionsEngine.EvaluateLanguageExpressionsRecursive(JToken root, ExpressionEvaluationContext evaluationContext, TemplateErrorAdditionalInfo additionalInfo, InsensitiveHashSet skipEvaluationPaths)
       at Microsoft.Azure.Templates.Analyzer.TemplateProcessor.ArmTemplateProcessor.ProcessTemplateResourceLanguageExpressions(TemplateResource templateResource, TemplateExpressionEvaluationHelper evaluationHelper)
```

I've tried understanding the exceptions, but I am not an ARM expert, and `az bicep` does not find any issues with the Bicep files.

Can you provide any guidance as to whether the exceptions are my doing, or a parsing error?
Thanks!

### Expected behavior

I expected the workflow to complete and upload the violations, as it has done in several other of my repos.

### Reproduction Steps

You can reproduce by running on https://github.com/pamelafox/simple-fastapi-container/

### Environment

Github Actions

**Comment by pamelafox** [comment]
Update: I figured out how to identify the fatal exceptions, by locating this section:

    	Summary of the errors:
    		1 instance of: An exception occurred while analyzing template /home/runner/work/simple-fastapi-container/simple-fastapi-container/infra/core/security/keyvault-access.bicep
    		1 instance of: An exception occurred while analyzing template /home/runner/work/simple-fastapi-container/simple-fastapi-container/infra/core/host/container-apps.bicep
    		1 instance of: An exception occurred while analyzing template /home/runner/work/simple-fastapi-container/simple-fastapi-container/infra/core/host/functions.bicep
    

I will close this issue and file follow-up issues if any of those aren't fixable on my end.
